### ISSUE TITLE
removeDups: should the function just error if a primary key is NA?

### ISSUE THREAD

**Issue by fluby** [NEONScience/NEON-OS-data-processing#3]
This behavior would make sense to me, as primary keys should really not be NA (but often are). An example I just had from running the function on the RELEASE-2022 mam_perplotnight table resulted in the following error message:

Primary key fields contain NA values and/or empty strings. Results may be unreliable; check input data carefully.
2 duplicated key values found, representing 4 non-unique records. Attempting to resolve.
  |==================================                                   |  50%Error in Ops.data.frame(data.dup[k, -which(colnames(data.dup) %in% c("uid",  : 
  ‘==’ only defined for equally-sized data frames

When I fixed the NA issue on the primary keys, the function ran without issue.

**Comment by cklunch** [comment]
@fluby There was some back-and-forth on this in the past, I think I left it this way because there are some cases where NAs are expected and the function works as usual. I'm open to revisiting. But I'm curious how you fixed the NAs, since the data are in a release?

**Comment by fluby** [comment]
@cklunch - fair enough. I just meant I fixed it for my data analysis, not in the NEON database.

**Comment by cklunch** [comment]
@fluby I'll give this some thought. It's theoretically possible to trace back to whether a given field was required, but I'm not sure that would address everything - e.g. the cases where you have to have either a tag or a barcode, but neither is formally required. But there are probably other approaches that would at least improve the situation.

**Comment by cklunch** [comment]
NA handling has been updated so that if **all** values in the primary key are NA, the data are flagged with -1, meaning "could not be evaluated". In theory this should never occur, but this is the mammal situation described above, and the duplicate checking can't reasonably function if this happens.

In situations where a subset of the key values are NA, removeDups() no longer prints a message. We'll keep an eye out for problems with this change.
